# A workspace for mitch's sketches!

[workspace]
members = [
    "aquatic-juice",
    "delicate-umbrella",
    "logo",
    "rainy-grandfather",
    "sloppy-roof",
    "soft-watch",
    "uppity-parcel",
]
resolver="2" 
